apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: wowsubscription
  namespace: default
spec:
  topic: order
  route: /dispatch/processorder
  pubsubname: wowpublish
scopes:
- dispatch-app
